---
# Example using a KubeconfigSecretRef
apiVersion: applications.argocd.crossplane.io/v1alpha1
kind: Application
metadata:
  name: example-application-kubeconfig
  namespace: example
spec:
  providerConfigRef:
    name: argocd-provider
  forProvider:
    destination:
      namespace: default
      name: example-cluster-kubeconfig
    project: default
    source:
      repoURL: https://github.com/stefanprodan/podinfo/
      path: charts/podinfo
      targetRevision: HEAD
