---
apiVersion: cluster.argocd.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: example-cluster-kubeconfig
  labels:
    purpose: dev
spec:
  forProvider:
    name: example-cluster-kubeconfig
    config:
      kubeconfigSecretRef:
        name: cluster-conn
        namespace: crossplane-system
        key: kubeconfig
  providerConfigRef:
    name: argocd-provider
