---
apiVersion: projects.argocd.crossplane.io/v1alpha1
kind: Project
metadata:
  name: example-project
spec:
  forProvider:
    description: "example project for e2e tests"
  providerConfigRef:
    name: argocd-provider
