---
apiVersion: applications.argocd.crossplane.io/v1alpha1
kind: Application
metadata:
  name: example-application
spec:
  forProvider:
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    source:
      repoURL: https://gitlab.com/example-group/example-project.git
  providerConfigRef:
    name: argocd-provider