---
apiVersion: repositories.argocd.crossplane.io/v1alpha1
kind: Repository
metadata:
  name: example-project.git
  namespace: example
spec:
  forProvider:
    repo: https://gitlab.com/example-group/example-project.git
    type: git
    username: example-user
    passwordRef:
      name: example-project.git
      namespace: crossplane-system
      key: token
  providerConfigRef:
    name: argocd-provider
---
apiVersion: repositories.argocd.crossplane.io/v1alpha1
kind: Repository
metadata:
  name: example-scoped-project.git
  namespace: example
spec:
  forProvider:
    project: example-project # project scoped repository
    repo: https://gitlab.com/example-group/example-project-scoped.git
    type: git
    username: example-user
    passwordRef:
      name: example-project.git
      namespace: crossplane-system
      key: token
  providerConfigRef:
    name: argocd-provider
