package converter

// Copy code generator interfaces from cluster to namespace
//go:generate go run -modfile ../../../../tools/go.mod -tags generate github.com/mistermx/copystruct/cmd/copycode ../../cluster/converter/applications ./applications client,conversions
//go:generate sed -i s|github\.com/crossplane-contrib/provider-argocd/apis/cluster|github.com/crossplane-contrib/provider-argocd/apis/namespace|g ./applications/zz_generated.copied.conversions.go
//go:generate sed -i s|github\.com/crossplane-contrib/provider-argocd/pkg/clients/cluster|github.com/crossplane-contrib/provider-argocd/pkg/clients/namespace|g ./applications/zz_generated.copied.conversions.go

//go:generate go run -modfile ../../../../tools/go.mod -tags generate github.com/mistermx/copystruct/cmd/copycode ../../cluster/converter/applicationsets ./applicationsets client,conversions
//go:generate sed -i s|github\.com/crossplane-contrib/provider-argocd/apis/cluster|github.com/crossplane-contrib/provider-argocd/apis/namespace|g ./applicationsets/zz_generated.copied.conversions.go
//go:generate sed -i s|github\.com/crossplane-contrib/provider-argocd/pkg/clients/cluster|github.com/crossplane-contrib/provider-argocd/pkg/clients/namespace|g ./applicationsets/zz_generated.copied.conversions.go

// Generate conversion code
//go:generate go run -modfile ../../../../tools/go.mod -tags generate github.com/jmattheis/goverter/cmd/goverter gen -output-constraint !ignore_autogenerated ./...
