// Code generated by copystruct. DO NOT EDIT.

package v1alpha1

import (
	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

// TokenParameters define the desired state of an ArgoCD Project Token
type TokenParameters struct {
	// Project is the project associated with the token
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-argocd/apis/namespace/projects/v1alpha1.Project
	// +crossplane:generate:reference:refFieldName=ProjectRef
	// +crossplane:generate:reference:selectorFieldName=ProjectSelector
	Project *string `json:"project"`

	// ProjectRefs is a reference to a Project used to set Project
	// +optional
	ProjectRef *v1.NamespacedReference `json:"projectRef,omitempty"`

	// ProjectSelector selects reference to a Project used to ProjectRef
	// +optional
	ProjectSelector *v1.NamespacedSelector `json:"projectSelector,omitempty"`

	// Role is the role associated with the token.
	Role string `json:"role"`

	// ID is an id for the token
	// +optional
	ID string `json:"id"`

	// Description is a description for the token
	// +optional
	Description *string `json:"description,omitempty"`

	// Duration before the token will expire. Valid time units are `s`, `m`, `h` and `d` E.g. 12h, 7d. No expiration if not set.
	// +optional
	// +kubebuilder:validation:Pattern=`^(0|[0-9]+(s|m|h|d))$`
	ExpiresIn *string `json:"expiresIn,omitempty"`

	// Duration to control token regeneration based on token age. Valid time units are `s`, `m`, `h` and `d`.
	// +optional
	// +kubebuilder:validation:Pattern=`^([0-9]+)(s|m|h|d)$`
	RenewAfter *string `json:"renewAfter,omitempty"`

	// Duration to control token regeneration based on remaining token lifetime. Valid time units are `s`, `m`, `h` and `d`.
	// +optional
	// +kubebuilder:validation:Pattern=`^([0-9]+)(s|m|h|d)$`
	RenewBefore *string `json:"renewBefore,omitempty"`
}

// TokenObservation holds the issuedAt and expiresAt values of a token
type TokenObservation struct {
	IssuedAt int64 `json:"iat"`
	// +optional
	ExpiresAt *int64 `json:"exp,omitempty"`
	// +optional
	ID *string `json:"id,omitempty"`
}
