---
apiVersion: cluster.argocd.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: example-cluster-kubeconfig
spec:
  forProvider:
    server: https://kubernetes.default.svc
    name: example-cluster-kubeconfig
    config:
      tlsClientConfig:
        insecure: true
  providerConfigRef:
    name: argocd-provider
